### PR TITLE
Use native tooltips to improve accessibility

### PR DESCRIPTION
**Pull request by tintou**
Tested in Ethercalc with french locale.
I also use a tiny html file testing socialcalc only.

### CODE REVIEW

**Comment by marcelklehr** [comment]
Wow, what a waste of code. :+1:

@eddyparkinson @audreyt What do you think?

**Comment by audreyt** [comment]
This changes the localized tooltips "Drag to lock pane vertically" and "Drag to lock pane horizontally" to the constant `paneslider`?

**Comment by marcelklehr** [comment]
Oh, I forgot about localization. Will l10n still work with this?

**Comment by tintou** [comment]
Oh, right, this one had a wrapper function that I just replaced with a small condition

**Comment by eddyparkinson** [comment]
@tintou Please add a summary of what has been tested.

I don't know this part of the code, I have never changed tool tips. As long as it has been tested and code reviewed, I am fine for it to be merged in.

**Comment by tintou** [comment]
I've tested it in ethercalc with the french locale, everything seems to work as expected.

**Comment by eddyparkinson** [comment]
will merge - native tooltips look to have been added to HTML 4.01 in 2002. So expect it will work on 99% of browsers.

**Pull request merged**
