### PR TITLE
Fix some exceptions

### PR DESCRIPTION
**Pull request by Chocobozzz**
Hello,

We are currently running an ethercalc instance (https://lite.framacalc.org/) but we had some exceptions. I tried to fix them. 

Sorry for the whitespaces, and some dirty fixes. Feel free to tell me if you want me to remove some of them.

### CODE REVIEW

**Review by eddyparkinson — APPROVED** [review]
Fixes undeclared var and add exception catch

**Comment by eddyparkinson** [comment]
Thanks for this, much appreciated.
Did all the changes get tested? Better to test all is working now rather than after the merge.

**Comment by Chocobozzz** [comment]
@eddyparkinson sure they are in production on our instance since a few weeks :)

**Comment by eddyparkinson** [comment]
@Chocobozzz sorry to be picky. Hope you don'e mind. Did every changed line of code get executed at least once. Was the result was as expected?  Checking every changed line of code has executed as expected is a good test. Sorry, I should have been clear last time I asked.

**Comment by Chocobozzz** [comment]
> Did every changed line of code get executed at least once

Yes, but it's rather every commit than every line of code. What happened:
 * We see an exception that crashes our instance
 * Search it, fix it, commit
 * The exception does not occur anymore

**Pull request merged**
