### PR TITLE
Fixed issue: =TEXTBOX in col A, unable to get focus audreyt/ethercalc#438

### PR DESCRIPTION
**Pull request by eddyparkinson**
Testing:
 added 3 textboxes - into A1, A2, B2 - all able to get focus in app mode

Signed-off-by: Eddy Parkinson

### CODE REVIEW

**Comment by marcelklehr** [comment]
:+1: for all your work! Let me know when to release a new version on npm. I could also add you as a maintainer, if you like.

**Comment by eddyparkinson** [comment]
>Let me know when to release a new version on npm

think all the changes over the last few days are save to release, as they are local impact changes. But I normally host a week on a staging server before putting
into the wild.

>I could also add you as a maintainer, if you like.

Please do. Is good to have a backup person for this.

**Comment by marcelklehr** [comment]
Sure. What's your npm account name?

**Comment by eddyparkinson** [comment]
@marcelklehr  Just created  https://www.npmjs.com/~eddyparkinson

**Comment by marcelklehr** [comment]
Great! you're now a maintainer on npm and can push new versions. :)

**Pull request merged**
